log_format client_log escape=none '[$time_local] [Frontend Client] $http_x_client_log_level: $http_x_client_log_msg';

server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location = /_client_log {
        access_log /dev/stdout client_log;
        default_type text/plain;
        return 204;
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
