{
 "title": "GTIO Observabilidad ECS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "dev,pre,pro" }
  ]
 },
 "panels": [
  {
   "title": "Uso de CPU - Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU Backend",
     "dimensions": { "ClusterName": "gtio-cluster-$environment", "ServiceName": "gtio-app-svc-$environment" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Uso de Memoria - Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Memoria Backend",
     "dimensions": { "ClusterName": "gtio-cluster-$environment", "ServiceName": "gtio-app-svc-$environment" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Errores HTTP 5xx (ALB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Errores 5xx",
     "dimensions": { "LoadBalancer": "app/gtio-alb-$environment" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Latencia de la Aplicacion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Latencia (Tiempo de respuesta)",
     "dimensions": { "LoadBalancer": "app/gtio-alb-$environment" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}